# Setup
title: DFAssist
tagline: FFXIV Duty Finder & F.A.T.E. Assist
baseurl: "/DFAssist"
paginate: 1

# About/contact
author:
  name: devunt
  url: https://github.com/devunt

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman